import{S as m,i as f}from"./assets/vendor-8c59ed88.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const n of e)if(n.type==="childList")for(const o of n.addedNodes)o.tagName==="LINK"&&o.rel==="modulepreload"&&s(o)}).observe(document,{childList:!0,subtree:!0});function i(e){const n={};return e.integrity&&(n.integrity=e.integrity),e.referrerPolicy&&(n.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?n.credentials="include":e.crossOrigin==="anonymous"?n.credentials="omit":n.credentials="same-origin",n}function s(e){if(e.ep)return;e.ep=!0;const n=i(e);fetch(e.href,n)}})();const h="https://pixabay.com/api/",y="44841461-2c7fd944dee0b14672f32444a",g="photo",$="horizontal",b=!0;function L(r){return fetch(`${h}?key=${y}&q=${r}&&image_type=${g}&orientation=${$}&safesearch=${b}`).then(t=>{if(!t.ok)throw new Error(t.status);return t.json()})}function v(r){return r.map(({largeImageURL:i,webformatURL:s,tags:e,views:n,downloads:o,likes:d,comments:p})=>`<li class="item-gallery">
    <a  class="gallery-link" href=${i}><img src="${s}" alt="${e}" title="${e}" width="360" height="200"></a>
    <div>
      <ul class="description-list">
        <li><p class="description-element">Like<br><span>${d}</span></p></li>
        <li><p class="description-element">Views<br><span>${n}</span></p></li>
        <li><p class="description-element">Comments<br><span>${p}</span></p></li>
        <li><p class="description-element">Downloads<br><span>${o}</span></p></li>
      </ul>
      </img>
  </li>
  </div>`).join(" ")}const S="Sorry, please enter text",q="Sorry, there are not no images matching your search query",w="Oops",O={gallery:document.querySelector(".gallery"),form:document.querySelector(".js-form"),loader:document.querySelector(".loader")},{gallery:a,form:u,loader:c}=O;u.addEventListener("submit",T);a.addEventListener("click",M);function M(r){r.preventDefault(),r.target.nodeName==="IMG"&&new m(".gallery a",{captionDelay:250,captionPosition:"bottom",captionsData:"alt"})}function T(r){r.preventDefault();const t=r.currentTarget;if(t.elements.query.value.trim()==="")return l("Warning",S);a.children.length&&(a.innerHTML=""),c.classList.remove("visually-hidden"),L(t.elements.query.value).then(i=>{k(i)}).catch(i=>l("Error",w,i)).finally(()=>{c.classList.add("visually-hidden"),u.reset()})}function k(r){if(r.hits.length===0)return l("Warning",q);const t=v(r.hits);a.insertAdjacentHTML("beforeend",t)}function l(r,t,i=null){return f.warning({title:`${r}`,message:i?`${t} ${i} `:`${t}`})}
//# sourceMappingURL=commonHelpers.js.map
